version: "2.1"  # optional since v1.27.0
services:
  service:
    image: dojitza/ispovesti.ml:service
    build:
      context: .
      dockerfile: service.Dockerfile
    ports:
      - "8100:8080"
  generator:
    image: dojitza/ispovesti.ml:generator
    build:
      context: .
      dockerfile: generator.Dockerfile
    deploy:
      resources:
        limits:
          memory: 10g
  broker:
    image: rabbitmq